"""
This type stub file was generated by pyright.
"""

import kagglehub.logger
from kagglehub import colab_cache_resolver, http_resolver, kaggle_cache_resolver, registry
from kagglehub.auth import login, whoami
from kagglehub.competition import competition_download
from kagglehub.datasets import dataset_download, dataset_upload
from kagglehub.models import model_download, model_upload

__version__ = ...
