"""
This type stub file was generated by pyright.
"""

from typing import Optional
from kagglehub.handle import ResourceHandle

DATASETS_CACHE_SUBFOLDER = ...
COMPETITIONS_CACHE_SUBFOLDER = ...
MODELS_CACHE_SUBFOLDER = ...
FILE_COMPLETION_MARKER_FOLDER = ...
def load_from_cache(handle: ResourceHandle, path: Optional[str] = ...) -> Optional[str]:
    """Return path for the requested resource from the cache.

    Args:
        handle: Resource handle
        path: Optional path to a file within the bundle.

    Returns:
        A string representing the path to the requested resource in the cache or None on cache miss.
    """
    ...

def get_cached_path(handle: ResourceHandle, path: Optional[str] = ...) -> str:
    ...

def get_cached_archive_path(handle: ResourceHandle) -> str:
    ...

def mark_as_complete(handle: ResourceHandle, path: Optional[str] = ...) -> None:
    ...

def mark_as_incomplete(handle: ResourceHandle, path: Optional[str] = ...) -> None:
    ...

def delete_from_cache(handle: ResourceHandle, path: Optional[str] = ...) -> Optional[str]:
    """Delete resource from the cache, even if incomplete.

    Args:
        handle: Resource handle
        path: Optional path to a file within the bundle.

    Returns:
        A string representing the path of the deleted resource or None on cache miss.
    """
    ...

