"""
This type stub file was generated by pyright.
"""

from typing import Optional
from kagglehub.handle import ModelHandle
from kagglehub.resolver import Resolver

COLAB_CACHE_MOUNT_FOLDER_ENV_VAR_NAME = ...
DEFAULT_COLAB_CACHE_MOUNT_FOLDER = ...
logger = ...
class ModelColabCacheResolver(Resolver[ModelHandle]):
    def is_supported(self, handle: ModelHandle, *_, **__) -> bool:
        ...
    
    def __call__(self, h: ModelHandle, path: Optional[str] = ..., *, force_download: Optional[bool] = ...) -> str:
        ...
    


