"""
This type stub file was generated by pyright.
"""

from typing import Optional

logger = ...
def competition_download(handle: str, path: Optional[str] = ..., *, force_download: Optional[bool] = ...) -> str:
    """Download competition dataset
    Args:
        handle: (string) the competition name
        path: (string) Optional path to a file within a competition dataset
        force_download: (bool) Optional flag to force download a competition dataset, even if it's cached
    Returns:
        A string requesting the path to the requested competition files.
    """
    ...

