"""
This type stub file was generated by pyright.
"""

import functools
from typing import Optional

KAGGLE_NOTEBOOK_ENV_VAR_NAME = ...
KAGGLE_DATA_PROXY_URL_ENV_VAR_NAME = ...
KAGGLE_TOKEN_KEY_DIR_ENV_VAR_NAME = ...
logger = ...
def is_in_colab_notebook() -> bool:
    ...

def is_in_kaggle_notebook() -> bool:
    ...

@functools.cache
def read_kaggle_build_date() -> str:
    ...

def search_lib_in_call_stack(lib_name: str) -> Optional[str]:
    """Search the call stack for a given library name and get its information.

    Args:
        lib_name (str):
            The name of the library to search for.
            We use str.startswith so the lib_name must match the exact module name from beginning.

    Returns:
        str: A formatted string f"{lib_name}/{lib_version}" if found, otherwise None.
    """
    ...

