"""
This type stub file was generated by pyright.
"""

import abc
from dataclasses import dataclass
from typing import Optional

"""Functions to parse resource handles."""
NUM_VERSIONED_DATASET_PARTS = ...
NUM_UNVERSIONED_DATASET_PARTS = ...
NUM_VERSIONED_MODEL_PARTS = ...
NUM_UNVERSIONED_MODEL_PARTS = ...
@dataclass
class ResourceHandle:
    @abc.abstractmethod
    def to_url(self) -> str:
        """Returns URL to the resource detail page."""
        ...
    


@dataclass
class ModelHandle(ResourceHandle):
    owner: str
    model: str
    framework: str
    variation: str
    version: Optional[int]
    def is_versioned(self) -> bool:
        ...
    
    def __str__(self) -> str:
        ...
    
    def to_url(self) -> str:
        ...
    


@dataclass
class DatasetHandle(ResourceHandle):
    owner: str
    dataset: str
    version: Optional[int] = ...
    def is_versioned(self) -> bool:
        ...
    
    def __str__(self) -> str:
        ...
    
    def to_url(self) -> str:
        ...
    


@dataclass
class CompetitionHandle(ResourceHandle):
    competition: str
    def __str__(self) -> str:
        ...
    
    def to_url(self) -> str:
        ...
    


def parse_dataset_handle(handle: str) -> DatasetHandle:
    ...

def parse_model_handle(handle: str) -> ModelHandle:
    ...

def parse_competition_handle(handle: str) -> CompetitionHandle:
    ...

