"""
This type stub file was generated by pyright.
"""

from typing import Optional
from kagglehub.handle import CompetitionHandle, DatasetHandle, ModelHandle
from kagglehub.resolver import Resolver

KAGGLE_CACHE_MOUNT_FOLDER_ENV_VAR_NAME = ...
ATTACH_DATASOURCE_REQUEST_NAME = ...
ATTACH_DATASOURCE_READ_TIMEOUT = ...
DEFAULT_KAGGLE_CACHE_MOUNT_FOLDER = ...
logger = ...
class CompetitionKaggleCacheResolver(Resolver[CompetitionHandle]):
    def is_supported(self, *_, **__) -> bool:
        ...
    
    def __call__(self, h: CompetitionHandle, path: Optional[str] = ..., *, force_download: Optional[bool] = ...) -> str:
        ...
    


class DatasetKaggleCacheResolver(Resolver[DatasetHandle]):
    def is_supported(self, *_, **__) -> bool:
        ...
    
    def __call__(self, h: DatasetHandle, path: Optional[str] = ..., *, force_download: Optional[bool] = ...) -> str:
        ...
    


class ModelKaggleCacheResolver(Resolver[ModelHandle]):
    def is_supported(self, *_, **__) -> bool:
        ...
    
    def __call__(self, h: ModelHandle, path: Optional[str] = ..., *, force_download: Optional[bool] = ...) -> str:
        ...
    


