"""
This type stub file was generated by pyright.
"""

from typing import Optional
from kagglehub.gcs_upload import UploadDirectoryInfo
from kagglehub.handle import ModelHandle

logger = ...
def create_model_instance_or_version(model_handle: ModelHandle, files: UploadDirectoryInfo, license_name: Optional[str], version_notes: str = ...) -> None:
    ...

def create_model_if_missing(owner_slug: str, model_slug: str) -> None:
    ...

def delete_model(owner_slug: str, model_slug: str) -> None:
    ...

