"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union

logger = ...
DEFAULT_IGNORE_PATTERNS = ...
def model_download(handle: str, path: Optional[str] = ..., *, force_download: Optional[bool] = ...) -> str:
    """Download model files.

    Args:
        handle: (string) the model handle.
        path: (string) Optional path to a file within the model bundle.
        force_download: (bool) Optional flag to force download a model, even if it's cached.


    Returns:
        A string representing the path to the requested model files.
    """
    ...

def model_upload(handle: str, local_model_dir: str, license_name: Optional[str] = ..., version_notes: str = ..., ignore_patterns: Optional[Union[list[str], str]] = ...) -> None:
    """Upload model files.

    Args:
        handle: (str) the model handle.
        local_model_dir: (str) path to a file in a local directory.
        license_name: (str) model license.
        version_notes: (str, optional) model versions.
        ignore_patterns (str or list[str], optional):
            Additional ignore patterns to DEFAULT_IGNORE_PATTERNS.
            Files matching any of the patterns are not uploaded.
            Patterns are standard wildcards that can be matched by
            https://docs.python.org/3/library/fnmatch.html.
            Use a pattern ending with "/" to ignore the whole dir,
            e.g., ".git/" is equivalent to ".git/*".
    """
    ...

