"""
This type stub file was generated by pyright.
"""

from typing import Callable

class MultiImplRegistry:
    """Utility class to inject multiple implementations of class.

    Each implementation must implement __call__ and is_supported with the same set of arguments. The registered
    implementations "is_supported" methods are called in reverse order under which they are registered. The first
    to return true is then invoked via __call__ and the result returned.
    """
    def __init__(self, name: str) -> None:
        ...
    
    def add_implementation(self, impl: Callable) -> None:
        ...
    
    def __call__(self, *args, **kwargs):
        ...
    


model_resolver = ...
dataset_resolver = ...
competition_resolver = ...
