"""
This type stub file was generated by pyright.
"""

import six

"""
    Kaggle API

    API for kaggle.com  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class TypeWithDefault(type):
    def __init__(cls, name, bases, dct) -> None:
        ...
    
    def __call__(cls): # -> Any:
        ...
    
    def set_default(cls, default): # -> None:
        ...
    


class Configuration(six.with_metaclass(TypeWithDefault, object)):
    """NOTE: This class is auto generated by the swagger code generator program.

    Ref: https://github.com/swagger-api/swagger-codegen
    Do not edit the class manually.
    """
    def __init__(self) -> None:
        """Constructor"""
        ...
    
    @property
    def logger_file(self):
        """The logger file.

        If the logger_file is None, then add stream handler and remove file
        handler. Otherwise, add file handler and remove stream handler.

        :param value: The logger_file path.
        :type: str
        """
        ...
    
    @logger_file.setter
    def logger_file(self, value): # -> None:
        """The logger file.

        If the logger_file is None, then add stream handler and remove file
        handler. Otherwise, add file handler and remove stream handler.

        :param value: The logger_file path.
        :type: str
        """
        ...
    
    @property
    def debug(self):
        """Debug status

        :param value: The debug status, True or False.
        :type: bool
        """
        ...
    
    @debug.setter
    def debug(self, value): # -> None:
        """Debug status

        :param value: The debug status, True or False.
        :type: bool
        """
        ...
    
    @property
    def logger_format(self):
        """The logger format.

        The logger_formatter will be updated when sets logger_format.

        :param value: The format string.
        :type: str
        """
        ...
    
    @logger_format.setter
    def logger_format(self, value): # -> None:
        """The logger format.

        The logger_formatter will be updated when sets logger_format.

        :param value: The format string.
        :type: str
        """
        ...
    
    def get_api_key_with_prefix(self, identifier): # -> None:
        """Gets API key (with prefix if set).

        :param identifier: The identifier of apiKey.
        :return: The token for api key authentication.
        """
        ...
    
    def get_basic_auth_token(self):
        """Gets HTTP basic authentication header (string).

        :return: The token for basic HTTP authentication.
        """
        ...
    
    def auth_settings(self): # -> dict[str, dict[str, Any]]:
        """Gets Auth Settings dict for api client.

        :return: The Auth Settings information dict.
        """
        ...
    
    def to_debug_report(self): # -> str:
        """Gets the essential information for debugging.

        :return: The report for debugging.
        """
        ...
    


