"""
This type stub file was generated by pyright.
"""

"""
    Kaggle API

    API for kaggle.com  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class Collaborator:
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    swagger_types = ...
    attribute_map = ...
    def __init__(self, username=..., role=...) -> None:
        """Collaborator - a model defined in Swagger"""
        ...
    
    @property
    def username(self): # -> None:
        """Gets the username of this Collaborator.  # noqa: E501

        Username of the collaborator  # noqa: E501

        :return: The username of this Collaborator.  # noqa: E501
        :rtype: str
        """
        ...
    
    @username.setter
    def username(self, username): # -> None:
        """Sets the username of this Collaborator.

        Username of the collaborator  # noqa: E501

        :param username: The username of this Collaborator.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def role(self): # -> None:
        """Gets the role of this Collaborator.  # noqa: E501

        Role of the collaborator  # noqa: E501

        :return: The role of this Collaborator.  # noqa: E501
        :rtype: str
        """
        ...
    
    @role.setter
    def role(self, role): # -> None:
        """Sets the role of this Collaborator.

        Role of the collaborator  # noqa: E501

        :param role: The role of this Collaborator.  # noqa: E501
        :type: str
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


