"""
This type stub file was generated by pyright.
"""

"""
    Kaggle API

    API for kaggle.com  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class ModelInstanceNewVersionRequest:
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    swagger_types = ...
    attribute_map = ...
    def __init__(self, version_notes=..., files=...) -> None:
        """ModelInstanceNewVersionRequest - a model defined in Swagger"""
        ...
    
    @property
    def version_notes(self): # -> None:
        """Gets the version_notes of this ModelInstanceNewVersionRequest.  # noqa: E501

        The version notes for the model instance version  # noqa: E501

        :return: The version_notes of this ModelInstanceNewVersionRequest.  # noqa: E501
        :rtype: str
        """
        ...
    
    @version_notes.setter
    def version_notes(self, version_notes): # -> None:
        """Sets the version_notes of this ModelInstanceNewVersionRequest.

        The version notes for the model instance version  # noqa: E501

        :param version_notes: The version_notes of this ModelInstanceNewVersionRequest.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def files(self): # -> None:
        """Gets the files of this ModelInstanceNewVersionRequest.  # noqa: E501

        A list of files that should be associated with the model instance version  # noqa: E501

        :return: The files of this ModelInstanceNewVersionRequest.  # noqa: E501
        :rtype: list[UploadFile]
        """
        ...
    
    @files.setter
    def files(self, files): # -> None:
        """Sets the files of this ModelInstanceNewVersionRequest.

        A list of files that should be associated with the model instance version  # noqa: E501

        :param files: The files of this ModelInstanceNewVersionRequest.  # noqa: E501
        :type: list[UploadFile]
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


