"""
This type stub file was generated by pyright.
"""

"""
    Kaggle API

    API for kaggle.com  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class UploadFile:
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    swagger_types = ...
    attribute_map = ...
    def __init__(self, token=..., description=..., columns=...) -> None:
        """UploadFile - a model defined in Swagger"""
        ...
    
    @property
    def token(self): # -> None:
        """Gets the token of this UploadFile.  # noqa: E501

        A token referencing a specific file upload that can be used across requests  # noqa: E501

        :return: The token of this UploadFile.  # noqa: E501
        :rtype: str
        """
        ...
    
    @token.setter
    def token(self, token): # -> None:
        """Sets the token of this UploadFile.

        A token referencing a specific file upload that can be used across requests  # noqa: E501

        :param token: The token of this UploadFile.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def description(self): # -> None:
        """Gets the description of this UploadFile.  # noqa: E501

        The file description  # noqa: E501

        :return: The description of this UploadFile.  # noqa: E501
        :rtype: str
        """
        ...
    
    @description.setter
    def description(self, description): # -> None:
        """Sets the description of this UploadFile.

        The file description  # noqa: E501

        :param description: The description of this UploadFile.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def columns(self): # -> None:
        """Gets the columns of this UploadFile.  # noqa: E501

        A list of dataset column metadata  # noqa: E501

        :return: The columns of this UploadFile.  # noqa: E501
        :rtype: list[DatasetColumn]
        """
        ...
    
    @columns.setter
    def columns(self, columns): # -> None:
        """Sets the columns of this UploadFile.

        A list of dataset column metadata  # noqa: E501

        :param columns: The columns of this UploadFile.  # noqa: E501
        :type: list[DatasetColumn]
        """
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    


